[[plugins]]
  package = "netlify-plugin-checklinks"

    [plugins.inputs]

    skipPatterns = ["#!", "www.google-analytics.com", "www.googletagmanager.com", "#main"]
    pretty = true

[[redirects]]
  from = "/docs/concept-overview"
  to = "/docs/concepts/introduction"

[[redirects]]
  from = "/docs/concept-workflows"
  to = "/docs/concepts/workflows"

[[redirects]]
  from = "/docs/concept-activities"
  to = "/docs/concepts/activities"

[[redirects]]
  from = "/docs/concept-signals"
  to = "/docs/concepts/signals"

[[redirects]]
  from = "/docs/concept-queries"
  to = "/docs/concepts/queries"

[[redirects]]
  from = "/docs/concept-task-queues"
  to = "/docs/concepts/task-queues"

[[redirects]]
  from = "/docs/concept-workers"
  to = "/docs/concepts/workers"

[[redirects]]
  from = "/docs/concept-namespaces"
  to = "/docs/server-namespaces"

[[redirects]]
  from = "/docs/go-execute-activity"
  to = "/docs/go-activities#executing-activities"

[[redirects]]
  from = "/docs/go-activity-async-completion"
  to = "/docs/go-activities#asynchronous-activity-completion"

[[redirect]]
  from = "/docs/java-sdk-overview"
  to = "/docs/java-sdk-introduction"

[[redirect]]
  from = "/docs/go-sdk-overview"
  to = "/docs/go-sdk-introduction"

[[redirect]]
  from = "/docs/php-sdk-overview"
  to = "/docs/php-sdk-introduction"

[[redirect]]
  from = "/docs/sdks-introduction"
  to = "/application-development"

[[redirects]]
  from = "/docs/use-cases-actors"
  to = "https://temporal.io/usecases#Actors"

[[redirects]]
  from = "/docs/use-cases-distributed-transactions"
  to = "https://temporal.io/usecases#transactions"

[[redirects]]
  from = "/docs/use-cases-dsl"
  to = "https://temporal.io/usecases#DSL"

[[redirects]]
  from = "/docs/use-cases-long-running"
  to = "https://temporal.io/usecases#Processes"

[[redirects]]
  from = "/docs/use-cases-monitoring"
  to = "https://temporal.io/usecases#Monitoring"

[[redirects]]
  from = "/docs/use-cases-orchestration"
  to = "https://temporal.io/usecases#orchestration"

[[redirects]]
  from = "/docs/use-cases-pipelines"
  to = "https://temporal.io/usecases#Pipelines"

[[redirects]]
  from = "/docs/use-cases-provisioning"
  to = "https://temporal.io/usecases#provisioning"

[[redirects]]
  from = "/docs/get-started"
  to = "/"

[[redirects]]
  from = "/docs/go-workflow-testing"
  to = "/docs/go-testing"
